### ISSUE TITLE
Tutorial out of date?

### ISSUE THREAD

**Issue by Teisi** [TYPO3-Documentation/TYPO3CMS-Tutorial-Templating#35]
Isn't this tutorial a bit outdated? Because it still uses "columns" (column normal and column right etc.).

https://docs.typo3.org/m/typo3/tutorial-templating/master/en-us/BasicFluidTemplates/Index.html

**Comment by AndrewMurphy2** [comment]
The tutorial does use the classic graphic design technique of columns in page layouts. We were trying to approach the topic from that angle, to provide context for a relatively broader audience just getting introduced to TYPO3. This angle is probably not yet obsolete.

The tutorial produces a dynamic page layout for one or two columns. At the time of writing, we put the second column on the right, so it made sense to use those terms. We fully tested the tutorial’s code before publishing in 2018, and have had no code corrections submitted since.

An intrepid editor could submit changes for the “normal” and “right” references, and then the new instructions should be thoroughly tested.

**Comment by linawolf** [comment]
The tutorial was archived
